### ISSUE TITLE
WAFInvalidParameterException Error While Creating WAF Rules

### ISSUE THREAD

**Issue by HarshitSF** [sourcefuse/terraform-aws-arc-waf#22]
I have defined **default action**  to allow for the web ACL and I am trying to **block** the action based on the Rules. But when I am configuring **action** parameter in **web_acl_rules** variable, I am getting below error -  

![image](https://github.com/sourcefuse/terraform-aws-arc-waf/assets/69293204/2a0b1b92-069a-4ede-bb08-665b6b41b163)

here is the dev.tfvars files which I am using.

```
region                      = ""
environment            = ""
namespace              = ""
web_acl_default_action = "allow"

web_acl_rules = [
  ## AWS-AWSManagedRulesAmazonIpReputationList
  {
    name     = "AWS-AWSManagedRulesAmazonIpReputationList"
    priority = 0
    action = [
      { block = [
        {
          custom_response = [ 
            {
            response_code = 404
          }
          ]
        }
        ]
      }
    ]
    override_action = [{ none = [{}] }]

    visibility_config = [
      {
        cloudwatch_metrics_enabled = true
        metric_name                = "AWS-AWSManagedRulesAmazonIpReputationList"
        sampled_requests_enabled   = true
      }
    ]

    statement = [
      {
        managed_rule_group_statement = [
          {
            name        = "AWSManagedRulesAmazonIpReputationList"
            vendor_name = "AWS"
          }
        ]
      }
    ]
  },]
```

**Comment by Mastansourcefuse** [comment]
I have fixed the previous issue which we are facing:**
Error:you have used none or multiple values that required a exaclty one value field: Rule Parameter: Rule
- **Fix Implemented**: 
  - Refactored the `managed_rule_group_statement` to properly reference the managed rule group 
  - Removed the invalid `override_action` in .tfvars which is not required.
  
After fixing that now we are getting the new error:
 
 Error: creating WAFv2 WebACL (waf): WAFInvalidParameterException: Error reason: A reference in your rule statement is not valid., field: RULE, parameter: Statement
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "5291665d-2ac1-4374-88bb-86232b70d8a3"
│   },
│   Field: "RULE",
│   Message_: "Error reason: A reference in your rule statement is not valid., field: RULE, parameter: Statement",
│   Parameter: "Statement",
│   Reason: "A reference in your rule statement is not valid."
│ }
│
│   with aws_wafv2_web_acl.this[0],
│   on main.tf line 19, in resource "aws_wafv2_web_acl" "this":
│   19: resource "aws_wafv2_web_acl" "this" {
│

Once this issue is resolved, I will proceed with testing and validating the Web ACL configuration.

**Comment by Mastansourcefuse** [comment]
Fix WAF rule configuration error by replacing `action` with override_action

The error documented in the description was caused by the incorrect use of the `action` block. This block only applies to rules for ip_set_reference_statement.

While override_action block only applies to rules with rule_group_reference_statement or managed_rule_group_statement .

To resolve this, @HarshitSF , in your case the override_action block (instead of action) should be the fix since the rule's statement is of type managed_rule_group_statement.
cc: @vijay-stephen 

For more details, refer to the Terraform documentation: https://www.terraform.io/docs/providers/aws/r/wafv2_web_acl.html#rules
https://github.com/hashicorp/terraform-provider-aws/issues/14120

<img width="702" alt="Screenshot 2024-11-13 170559" src="https://github.com/user-attachments/assets/af107932-d333-4ff3-a44f-22a1aa2e14c0">


dev.tfvars

````
# General Web ACL Information
# namespace ="dev"
# environment ="poc"
web_acl_name           = "waf"
web_acl_default_action = "allow"

# Setting the visibility config for CloudWatch metrics
web_acl_visibility_config = {
  cloudwatch_metrics_enabled = true
  metric_name                = "AWS-AWSManagedRulesAmazonIpReputationList"
  sampled_requests_enabled   = true
}

web_acl_rules = [
  {
    name     = "AWS-AWSManagedRulesAmazonIpReputationList"
    priority = 0

    override_action = [{ none = [{}] }]

    visibility_config = [
      {
        cloudwatch_metrics_enabled = true
        metric_name                = "AWS-AWSManagedRulesAnonymousIpList"
        sampled_requests_enabled   = true
      }
    ]
    statement = [
      {
        managed_rule_group_statement = [
          {
            name        = "AWSManagedRulesAmazonIpReputationList"
            vendor_name = "AWS"
          }
        ]
      }
    ]
  },




  # Rate-Based Rule Example
  {
    name     = "RateLimitRule"
    priority = 1
    action = [
      {
        block = [
          {
            custom_response = [
              {
                response_code = 429
              }
            ]
          }
        ]
      }
    ]
    visibility_config = [
      {
        cloudwatch_metrics_enabled = true
        metric_name                = "RateLimitRuleMetric"
        sampled_requests_enabled   = true
      }
    ]
    statement = [
      {
        rate_based_statement = [
          {
            limit              = 1000 # Limit of 1000 requests in 5 minutes
            aggregate_key_type = "IP" # Match requests from the same IP
          }
        ]
      }
    ]
  }
]
`


```

```
```

**Comment by HarshitSF** [comment]
Thanks @Mastansourcefuse  for the explanation.
